#!/usr/bin/env bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

if [ "$(type -t set_env_var)" == "function" ]; then
    set_env_var 'BUNDLE_WITHOUT' 'development test' $OPENSHIFT_HOMEDIR/.env/user_vars
fi
