#!/usr/bin/env bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

if [ -z "$BUNDLE_WITHOUT" ]; then
    export BUNDLE_WITHOUT='development test'
    if [ "$(type -t set_env_var)" == "function" ]; then
        set_env_var 'BUNDLE_WITHOUT' "$BUNDLE_WITHOUT" $OPENSHIFT_HOMEDIR/.env/user_vars
    fi
fi
